@startuml inline_umlgraph_1.svg
start

partition "**process** MainThread" {

    :**Main.c**
    Main caller function;

    if (condition met?) then
        #lightblue:**testFunctions.c**
        Design a new implementation idea!
        Super cool;
        end
    endif

    #lightblue:repeat : testing;
        :read data;
    backward: This is going back;
    repeat while (more data?) is (yes)
    ->no;

    stop

}
@enduml
